apiVersion: v1
name: rke2-kube-proxy
description: Install Kube Proxy.
version: v1.21.4-rke2r4-build20210909
appVersion: v1.21.4-rke2r4
keywords:
  - kube-proxy
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
