url: https://github.com/projectcalico/calico/releases/download/v3.21.4/tigera-operator-v3.21.4.tgz
packageVersion: 02
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
